Library/ViewModels/Books/CreateBookViewModel.cs
using System.ComponentModel.DataAnnotations;

namespace Library.ViewModels.Books
{
    public class CreateBookViewModel
    {
        [Required]
        [MaxLength(64)]
        public string Title { get; set; }

        [MaxLength(255)]
        public string Description { get; set; }

        public IFormFile? ImageFile { get; set; }
    }
}

Library/ViewModels/Books/EditBookViewModel.cs
using System.ComponentModel.DataAnnotations;

namespace Library.ViewModels.Books
{
    public class EditBookViewModel
    {
        public string Id { get; set; }
        [Required]
        [MaxLength(64)]
        public string Title { get; set; }

        [MaxLength(255)]
        public string Description { get; set; }
    }
}

Library/ViewModels/Books/IndexBookViewModel.cs
using System.ComponentModel.DataAnnotations;

namespace Library.ViewModels.Books
{
    public class IndexBookViewModel
    {
        public string Id { get; set; }

        public string Title { get; set; }

        [Display(Name = "Picture")]
        public string Image { get; set; }
    }
}

Library/ViewModels/Books/IndexBooksViewModel.cs
using Library.ViewModels.Authors;

namespace Library.ViewModels.Books
{
    public class IndexBooksViewModel : PagingViewModel
    {
        public IndexBooksViewModel():base(10){}
        public IndexBooksViewModel(int elementsCount, int itemsPerPage = 5, string action = "Index") : base(elementsCount, itemsPerPage, action)
        {
        }

        public string FilterByTitle { get; set; }

        public bool IsAsc { get; set; } = true;

        public ICollection<IndexBookViewModel> Books { get; set; } = new List<IndexBookViewModel>();
    }
}

Library/Controllers/BookRatingsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Library.Data;
using Library.Data.Models;
using Library.ViewModels.Ratings;
using Library.Services.Contracts;
using System.Security.Claims;
using Microsoft.AspNetCore.Authorization;
using Library.ViewModels.BookRatings;

namespace Library.Controllers
{
    [Authorize]
    public class BookRatingsController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly IBookRatingsService bookRatingsService;

        public BookRatingsController(ApplicationDbContext context, IBookRatingsService bookRatingsService)
        {
            _context = context;
            this.bookRatingsService = bookRatingsService;
        }

        // GET: BookRatings
        [Authorize(Roles = GlobalConstants.AdminRole)]
        public async Task<IActionResult> Index()
        {
            var applicationDbContext = _context.Ratings.Include(b => b.Author).Include(b => b.User);
            return View(await applicationDbContext.ToListAsync());
        }

        public async Task<IActionResult> UserIndex(IndexBookRatingsUserViewModel userBookRatings)
        {
            var userId = this.User.FindFirst(ClaimTypes.NameIdentifier).Value;
            userBookRatings = await bookRatingsService.GetUserBookRatingsAsync(userBookRatings, userId);

            return View(userBookRatings);
        }

        // GET: BookRatings/Details/5
        public async Task<IActionResult> Details(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var bookRating = await _context.Ratings
                .Include(b => b.Author)
                .Include(b => b.User)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (bookRating == null)
            {
                return NotFound();
            }

            return View(bookRating);
        }

        // GET: BookRatings/Create
        public IActionResult Create(string authorId)
        {
            CreateBookRatingViewModel model = new CreateBookRatingViewModel();
            model.AuthorId = authorId;
            return View(model);
        }

        // POST: BookRatings/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(CreateBookRatingViewModel bookRating)
        {
            if (ModelState.IsValid)
            {
                var userId = this.User.FindFirst(ClaimTypes.NameIdentifier).Value;
                await bookRatingsService.CreateBookRatingAsync(bookRating, userId);
                return RedirectToAction(nameof(UserIndex));
            }
            return View(bookRating);
        }

        // GET: BookRatings/Edit/5
        public async Task<IActionResult> Edit(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var bookRating = await _context.Ratings.FindAsync(id);
            if (bookRating == null)
            {
                return NotFound();
            }
            ViewData["AuthorId"] = new SelectList(_context.Authors, "Id", "Id", bookRating.AuthorId);
            ViewData["UserId"] = new SelectList(_context.Users, "Id", "Id", bookRating.UserId);
            return View(bookRating);
        }

        // POST: BookRatings/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(string id, [Bind("Id,UserId,AuthorId,Rating,Review")] BookRating bookRating)
        {
            if (id != bookRating.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(bookRating);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!BookRatingExists(bookRating.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["AuthorId"] = new SelectList(_context.Authors, "Id", "Id", bookRating.AuthorId);
            ViewData["UserId"] = new SelectList(_context.Users, "Id", "Id", bookRating.UserId);
            return View(bookRating);
        }

        // GET: BookRatings/Delete/5
        public async Task<IActionResult> Delete(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var bookRating = await _context.Ratings
                .Include(b => b.Author)
                .Include(b => b.User)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (bookRating == null)
            {
                return NotFound();
            }

            return View(bookRating);
        }

        // POST: BookRatings/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(string id)
        {
            var bookRating = await _context.Ratings.FindAsync(id);
            if (bookRating != null)
            {
                _context.Ratings.Remove(bookRating);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool BookRatingExists(string id)
        {
            return _context.Ratings.Any(e => e.Id == id);
        }
    }
}

Library/Controllers/BooksController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Library.Data;
using Library.Data.Models;
using Library.ViewModels.Books;
using Library.Services.Contracts;
using Library.Services;
using Library.ViewModels.Authors;

namespace Library.Controllers
{
    public class BooksController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly IBooksService booksService;

        public BooksController(ApplicationDbContext context, IBooksService booksService)
        {
            _context = context;
            this.booksService = booksService;
        }

        // GET: Books
        public async Task<IActionResult> Index(IndexBooksViewModel books)
        {
            books = await booksService.GetBooksAsync(books);
            return View(books);
        }

        // GET: Books/Details/5
        public async Task<IActionResult> Details(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var book = await _context.Books
                .FirstOrDefaultAsync(m => m.Id == id);
            if (book == null)
            {
                return NotFound();
            }

            return View(book);
        }

        // GET: Books/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Books/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(CreateBookViewModel book)
        {
            if (ModelState.IsValid)
            {
               await booksService.CreateBookAsync(book);
                return RedirectToAction(nameof(Index));
            }
            return View(book);
        }

        // GET: Books/Edit/5
        public async Task<IActionResult> Edit(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var book = await booksService.GetBookToEditAsync(id);
            if (book == null)
            {
                return NotFound();
            }
            return View(book);
        }

        // POST: Books/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(EditBookViewModel editBook)
        {
            if (ModelState.IsValid)
            {
                await booksService.UpdateBookAsync(editBook);
                return RedirectToAction(nameof(Index));
            }
            return View(editBook);
        }

        // GET: Books/Delete/5
        public async Task<IActionResult> Delete(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var book = await _context.Books
                .FirstOrDefaultAsync(m => m.Id == id);
            if (book == null)
            {
                return NotFound();
            }

            return View(book);
        }

        // POST: Books/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(string id)
        {
            var book = await _context.Books.FindAsync(id);
            if (book != null)
            {
                _context.Books.Remove(book);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool BookExists(string id)
        {
            return _context.Books.Any(e => e.Id == id);
        }
        public async Task<IActionResult> Seed()
        {
            IFormFile file = ConvertToIFormFile("C:\\Users\\HP\\Desktop\\Library\\Library\\Library\\wwwroot\\img\\defBook.jpg");
            for (int i = 0; i < 40; i++)
            {
                CreateBookViewModel model = new CreateBookViewModel()
                {
                    Title = $"Book {i}",
                    Description = $"Description for book {i}",
                    ImageFile = file
                };
                await booksService.CreateBookAsync(model);
            }
            return RedirectToAction(nameof(Index));
        }
        public IFormFile ConvertToIFormFile(string filePath)
        {
            var fileInfo = new FileInfo(filePath);
            var fileStream = new FileStream(filePath, FileMode.Open);

            IFormFile formFile = new FormFile(fileStream, 0, fileInfo.Length, fileInfo.Name, fileInfo.Name)
            {
                Headers = new HeaderDictionary(),
                ContentType = "application/octet-stream"
            };

            return formFile;
        }
    }
}

Library/Views/Books/Create.cshtml
@model CreateBookViewModel

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>Book</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create" enctype="multipart/form-data">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Title" class="control-label"></label>
                <input asp-for="Title" class="form-control" />
                <span asp-validation-for="Title" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Description" class="control-label"></label>
                <input asp-for="Description" class="form-control" />
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ImageFile" class="control-label"></label>
                <input asp-for="ImageFile" class="form-control" />
                <span asp-validation-for="ImageFile" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Library/Views/Books/Delete.cshtml
@model Library.Data.Models.Book

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Book</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Title)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Title)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Description)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Description)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Image)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Image)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

Library/Views/Books/Details.cshtml
@model Library.Data.Models.Book

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>Book</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Title)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Title)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Description)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Description)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Image)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Image)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model?.Id">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

Library/Views/Books/Edit.cshtml
@model EditBookViewModel

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>Book</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="Title" class="control-label"></label>
                <input asp-for="Title" class="form-control" />
                <span asp-validation-for="Title" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Description" class="control-label"></label>
                <input asp-for="Description" class="form-control" />
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Library/Views/Books/Index.cshtml
@model IndexBooksViewModel

@{
    Dictionary<string, string> routs = new Dictionary<string, string>()
    {
        {"filterByName", Model.FilterByTitle },
        {"isAsc",Model.IsAsc.ToString()},
        {"itemsPerPage",Model.ItemsPerPage.ToString()}
    };
}

<h2>Books page</h2>
<a asp-action="Create" class="btn btn-primary">Create</a>
<hr />
<form asp-action="Index" method="get">
    <div class="input-group mb-3">
        <button type="submit" class="btn btn-outline-secondary">Search</button>
        <input asp-for="FilterByTitle" type="text" class="form-control" placeholder="Title" aria-label="Search" aria-describedby="basic-addon2">
    </div>
</form>
<table class="table table-bordered table-striped table-hover">
    <thead>
        <tr>
            <th>
                @{
                    routs["sortUsersBy"] = "Name";

                }
                <a asp-all-route-data="routs">Full name</a>
            </th>
            Picture
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var book in Model.Books)
        {
            <tr>
                <td>
                    @book.Title
                </td>
                <td>
                    <img src="data:image/png;base64,@Html.DisplayFor(modelItem => book.Image)" width="300" height="200">
                </td>
                <td>
                    <a asp-action="Create" asp-controller="BookRatings" asp-route-bookId="@book.Id" class="btn btn-sm btn-secondary">BookRatings</a>
                    @if (this.User.IsInRole("Admin"))
                    {
                        <a asp-action="Edit" asp-action="Edit" asp-route-id="@book.Id" class="btn btn-sm btn-secondary">Edit</a>
                        <a asp-action="Delete" asp-route-id="@book.Id" class="btn btn-sm btn-danger">Delete</a>
                    }
                </td>
            </tr>
        }
    </tbody>
</table>

<nav aria-label="..." class="">
    <ul class="pagination  justify-content-center">
        <li style="margin-right:5px">
            <form asp-action="@Model.Action" method="post" id="pageSizeForm">

                <select asp-for="ItemsPerPage" class="form-control border-dark" onchange="changeItemsPerPage();">
                    <option value="5">5</option>
                    <option value="10">10</option>
                    <option value="25">25</option>
                    <option value="50">50</option>
                </select>

                <input type="submit" id="loginSubmit" style="visibility:hidden" />
            </form>
        </li>
        <li class="page-item @if (!Model.HasPreviousPage) {
        <text>disabled</text>
 }">
            <a class="page-link" asp-action="@Model.Action"  asp-all-route-data="routs" asp-route-page="@Model.PreviousPageNumber">
                <i class="fas fa-step-backward"></i>

            </a>
        </li>
        @for (int i = Model.Page - 2; i < Model.Page; i++)
        {
            if (i > 0)
            {
                <li class="page-item"><a class="page-link" asp-action="@Model.Action" asp-all-route-data="routs" asp-route-page="@i">@i</a></li>
            }
        }
        <li class="page-item active" aria-current="page">
            <span class="page-link">
                @Model.Page
                <span class="sr-only">(current)</span>
            </span>
        </li>
        @for (int i = Model.Page + 1; i <= Model.Page + 2; i++)
        {
            if (i <= Model.PagesCount)
            {
                <li class="page-item"><a class="page-link" asp-action="@Model.Action" asp-all-route-data="routs" asp-route-page="@i">@i</a></li>
            }
        }
        <li class="page-item @if (!Model.HasNextPage) {
        <text>disabled</text>
 }">
            <a class="page-link" asp-action="@Model.Action" asp-all-route-data="routs" asp-route-page="@Model.NextPageNumber" ><i class="fas fa-step-forward"></i></a>
        </li>
    </ul>
</nav>

<script type="text/javascript">

    function changeItemsPerPage() {

        document.getElementById('pageSizeForm').submit();
    }
</script>