Library/ViewModels/Authors/CreateAuthorViewModel.cs
using System.ComponentModel.DataAnnotations;

namespace Library.ViewModels.Authors
{
    public class CreateAuthorViewModel
    {
        [Required]
        [MaxLength (64)]
        public string Name { get; set; }

        [MaxLength (255)]
        public string Description { get; set; }

        public IFormFile? ImageFile { get; set; }
    }
}

Library/ViewModels/Authors/EditAuthorViewModel.cs
using System.ComponentModel.DataAnnotations;

namespace Library.ViewModels.Authors
{
    public class EditAuthorViewModel
    {
        public string Id { get; set; }

        [Required]
        [MaxLength(64)]
        public string Name { get; set; }

        [MaxLength(255)]
        public string Description { get; set; }
    }
}

Library/ViewModels/Authors/IndexAuthorViewModel.cs
using System.ComponentModel.DataAnnotations;

namespace Library.ViewModels.Authors
{
    public class IndexAuthorViewModel
    {
        public string Id { get; set; }

        public string Name { get; set; }

        [Display (Name = "Picture")]
        public string Image { get; set; }
    }
}

Library/ViewModels/Authors/IndexAuthorsViewModel.cs
namespace Library.ViewModels.Authors
{
    public class IndexAuthorsViewModel : PagingViewModel
    {
        public IndexAuthorsViewModel():base(10)
        {
            
        }
        public IndexAuthorsViewModel(int elementsCount, int itemsPerPage = 10, string action = "Index") : base(elementsCount, itemsPerPage, action)
        {
        }

        public string FilterByName { get; set; }

        public bool IsAsc { get; set; } = true;

        public ICollection<IndexAuthorViewModel> Authors { get; set; } = new List<IndexAuthorViewModel>();
    }
}

Library/Controllers/AuthorRatingsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Library.Data;
using Library.Data.Models;
using Library.ViewModels.Ratings;
using Library.Services.Contracts;
using System.Security.Claims;
using Microsoft.AspNetCore.Authorization;
using Library.ViewModels.AuthorRatings;

namespace Library.Controllers
{
    [Authorize]
    public class AuthorRatingsController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly IAuthorRatingsService AuthorRatingsService;

        public AuthorRatingsController(ApplicationDbContext context, IAuthorRatingsService AuthorRatingsService)
        {
            _context = context;
            this.AuthorRatingsService = AuthorRatingsService;
        }

        // GET: AuthorRatings
        [Authorize(Roles = GlobalConstants.AdminRole)]
        public async Task<IActionResult> Index()
        {
            var applicationDbContext = _context.Ratings.Include(b => b.Author).Include(b => b.User);
            return View(await applicationDbContext.ToListAsync());
        }

        public async Task<IActionResult> UserIndex(IndexAuthorRatingsUserViewModel userAuthorRatings)
        {
            var userId = this.User.FindFirst(ClaimTypes.NameIdentifier).Value;
            userAuthorRatings = await AuthorRatingsService.GetUserAuthorRatingsAsync(userAuthorRatings, userId);

            return View(userAuthorRatings);
        }

        // GET: AuthorRatings/Details/5
        public async Task<IActionResult> Details(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var AuthorRating = await _context.Ratings
                .Include(b => b.Author)
                .Include(b => b.User)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (AuthorRating == null)
            {
                return NotFound();
            }

            return View(AuthorRating);
        }

        // GET: AuthorRatings/Create
        public IActionResult Create(string authorId)
        {
            CreateAuthorRatingViewModel model = new CreateAuthorRatingViewModel();
            model.AuthorId = authorId;
            return View(model);
        }

        // POST: AuthorRatings/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(CreateAuthorRatingViewModel AuthorRating)
        {
            if (ModelState.IsValid)
            {
                var userId = this.User.FindFirst(ClaimTypes.NameIdentifier).Value;
                await AuthorRatingsService.CreateAuthorRatingAsync(AuthorRating, userId);
                return RedirectToAction(nameof(UserIndex));
            }
            return View(AuthorRating);
        }

        // GET: AuthorRatings/Edit/5
        public async Task<IActionResult> Edit(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var AuthorRating = await _context.Ratings.FindAsync(id);
            if (AuthorRating == null)
            {
                return NotFound();
            }
            ViewData["AuthorId"] = new SelectList(_context.Authors, "Id", "Id", AuthorRating.AuthorId);
            ViewData["UserId"] = new SelectList(_context.Users, "Id", "Id", AuthorRating.UserId);
            return View(AuthorRating);
        }

        // POST: AuthorRatings/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(string id, [Bind("Id,UserId,AuthorId,Rating,Review")] AuthorRating AuthorRating)
        {
            if (id != AuthorRating.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(AuthorRating);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!AuthorRatingExists(AuthorRating.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["AuthorId"] = new SelectList(_context.Authors, "Id", "Id", AuthorRating.AuthorId);
            ViewData["UserId"] = new SelectList(_context.Users, "Id", "Id", AuthorRating.UserId);
            return View(AuthorRating);
        }

        // GET: AuthorRatings/Delete/5
        public async Task<IActionResult> Delete(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var AuthorRating = await _context.Ratings
                .Include(b => b.Author)
                .Include(b => b.User)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (AuthorRating == null)
            {
                return NotFound();
            }

            return View(AuthorRating);
        }

        // POST: AuthorRatings/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(string id)
        {
            var AuthorRating = await _context.Ratings.FindAsync(id);
            if (AuthorRating != null)
            {
                _context.Ratings.Remove(AuthorRating);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool AuthorRatingExists(string id)
        {
            return _context.Ratings.Any(e => e.Id == id);
        }
        public async Task<IActionResult> Seed()
        {
            await AuthorRatingsService.SeedReviewsAsync();
            return RedirectToAction(nameof(Index));
        }
    }
}

Library/Controllers/AuthorsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Library.Data;
using Library.Data.Models;
using Library.ViewModels.Authors;
using Library.Services.Contracts;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Cors.Infrastructure;

namespace Library.Controllers
{
    public class AuthorsController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly IAuthorsService authorsService;

        public AuthorsController(ApplicationDbContext context, IAuthorsService authorsService)
        {
            _context = context;
            this.authorsService = authorsService;
        }

        // GET: Authors
        public async Task<IActionResult> Index(IndexAuthorsViewModel authors)
        {
            authors = await authorsService.GetAuthorsAsync(authors);
            return View(authors);
        }

        // GET: Authors/Details/5
        public async Task<IActionResult> Details(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var author = await _context.Authors
                .FirstOrDefaultAsync(m => m.Id == id);
            if (author == null)
            {
                return NotFound();
            }

            return View(author);
        }

        // GET: Authors/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Authors/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [Authorize(Roles = GlobalConstants.AdminRole)]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(CreateAuthorViewModel author)
        {
            if (ModelState.IsValid)
            {
                await authorsService.CreateAuthorAsync(author);
                return RedirectToAction(nameof(Index));
            }
            return View(author);
        }

        // GET: Authors/Edit/5
        public async Task<IActionResult> Edit(string id)
        {
            if (id == null)
            {
                return NotFound();
            }
            var author = await authorsService.GetAuthorToEditAsync(id);

            if (author == null)
            {
                return NotFound();
            }
            return View(author);
        }

        // POST: Authors/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(EditAuthorViewModel editAuthor)
        {
            if (ModelState.IsValid)
            {
                await authorsService.UpdateAuthorAsync(editAuthor);
                return RedirectToAction(nameof(Index));
            }
            return View(editAuthor);
        }

        // GET: Authors/Delete/5
        public async Task<IActionResult> Delete(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var author = await _context.Authors
                .FirstOrDefaultAsync(m => m.Id == id);
            if (author == null)
            {
                return NotFound();
            }

            return View(author);
        }

        // POST: Authors/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(string id)
        {
            var author = await _context.Authors.FindAsync(id);
            if (author != null)
            {
                _context.Authors.Remove(author);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool AuthorExists(string id)
        {
            return _context.Authors.Any(e => e.Id == id);
        }

        public async Task<IActionResult> Seed()
        {
            IFormFile file = ConvertToIFormFile("C:\\Users\\HP\\Desktop\\Library\\Library\\Library\\wwwroot\\img\\avtordef.jpg");
            for (int i = 0; i < 40; i++)
            {
                CreateAuthorViewModel model = new CreateAuthorViewModel()
                {
                    Name = $"Author {i}",
                    Description = $"Description for author {i}",
                    ImageFile = file
                };
                await authorsService.CreateAuthorAsync(model);
            }
            return RedirectToAction(nameof(Index));
        }
        public IFormFile ConvertToIFormFile(string filePath)
        {
            var fileInfo = new FileInfo(filePath);
            var fileStream = new FileStream(filePath, FileMode.Open);

            IFormFile formFile = new FormFile(fileStream, 0, fileInfo.Length, fileInfo.Name, fileInfo.Name)
            {
                Headers = new HeaderDictionary(),
                ContentType = "application/octet-stream"
            };

            return formFile;
        }
    }
}

Library/Views/Authors/Create.cshtml
@model CreateAuthorViewModel

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>Author</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create" enctype="multipart/form-data">

            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Description" class="control-label"></label>
                <input asp-for="Description" class="form-control" />
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ImageFile" class="control-label"></label>
                <input asp-for="ImageFile" class="form-control" />
                <span asp-validation-for="ImageFile" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Library/Views/Authors/Delete.cshtml
@model Library.Data.Models.Author

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Author</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Description)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Description)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Image)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Image)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

Library/Views/Authors/Details.cshtml
@model Library.Data.Models.Author

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>Author</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Description)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Description)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Image)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Image)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model?.Id">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

Library/Views/Authors/Edit.cshtml
@model EditAuthorViewModel

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>Author</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Description" class="control-label"></label>
                <input asp-for="Description" class="form-control" />
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Library/Views/Authors/Index.cshtml
@model IndexAuthorsViewModel

@{
    Dictionary<string, string> routs = new Dictionary<string, string>()
    {
        {"filterByName", Model.FilterByName },
        {"isAsc",Model.IsAsc.ToString()},
        {"itemsPerPage",Model.ItemsPerPage.ToString()}
    };
}

<h2>Authors page</h2>
<a asp-action="Create" class="btn btn-primary">Create</a>
<hr />
<form asp-action="Index" method="get">
    <div class="input-group mb-3">
        <button type="submit" class="btn btn-outline-secondary">Search</button>
        <input asp-for="FilterByName" type="text" class="form-control" placeholder="Name" aria-label="Search" aria-describedby="basic-addon2">
    </div>
</form>
<table class="table table-bordered table-striped table-hover">
    <thead>
        <tr>
            <th>
                @{
                    routs["sortUsersBy"] = "Name";

                }
                <a asp-all-route-data="routs">Full name</a>
            </th>
          Picture
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var author in Model.Authors)
        {
            <tr>
                <td>
                    @author.Name
                </td>
                <td>
                    <img src="data:image/png;base64,@Html.DisplayFor(modelItem => author.Image)" width="300" height="200">
                </td>
                <td>
                    <a asp-action="Create" asp-controller="AuthorRatings" asp-route-authorId="@author.Id" class="btn btn-sm btn-secondary">AuthorRatings</a>
                    @if (this.User.IsInRole("Admin"))
                    {
                        <a  asp-action="Edit" asp-route-id="@author.Id" class="btn btn-sm btn-secondary">Edit</a>
                        <a asp-action="Delete" asp-route-id="@author.Id" class="btn btn-sm btn-danger">Delete</a>
                    }
                </td>
            </tr>
        }
    </tbody>
</table>

<nav aria-label="..." class="">
    <ul class="pagination  justify-content-center">
        <li style="margin-right:5px">
            <form asp-action="@Model.Action" method="post" id="pageSizeForm">

                <select asp-for="ItemsPerPage" class="form-control border-dark" onchange="changeItemsPerPage();">
                    <option value="5">5</option>
                    <option value="10">10</option>
                    <option value="25">25</option>
                    <option value="50">50</option>
                </select>

                <input type="submit" id="loginSubmit" style="visibility:hidden" />
            </form>
        </li>
        <li class="page-item @if (!Model.HasPreviousPage) {
        <text>disabled</text>
 }">
            <a class="page-link" asp-action="@Model.Action"  asp-all-route-data="routs" asp-route-page="@Model.PreviousPageNumber">
                <i class="fas fa-step-backward"></i>

            </a>
        </li>
        @for (int i = Model.Page - 2; i < Model.Page; i++)
        {
            if (i > 0)
            {
                <li class="page-item"><a class="page-link" asp-action="@Model.Action" asp-all-route-data="routs" asp-route-page="@i">@i</a></li>
            }
        }
        <li class="page-item active" aria-current="page">
            <span class="page-link">
                @Model.Page
                <span class="sr-only">(current)</span>
            </span>
        </li>
        @for (int i = Model.Page + 1; i <= Model.Page + 2; i++)
        {
            if (i <= Model.PagesCount)
            {
                <li class="page-item"><a class="page-link" asp-action="@Model.Action" asp-all-route-data="routs" asp-route-page="@i">@i</a></li>
            }
        }
        <li class="page-item @if (!Model.HasNextPage) {
        <text>disabled</text>
 }">
            <a class="page-link" asp-action="@Model.Action" asp-all-route-data="routs" asp-route-page="@Model.NextPageNumber" ><i class="fas fa-step-forward"></i></a>
        </li>
    </ul>
</nav>

<script type="text/javascript">

    function changeItemsPerPage() {

        document.getElementById('pageSizeForm').submit();
    }
</script>